name: premierchoixapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.








# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  firebase_storage: ^3.1.5
  flutter_spinkit: ^4.1.2+1
  page_transition: ^1.1.5
  curved_navigation_bar: ^0.3.2
  email_validator: ^1.0.4
  flutter_star_rating: ^0.0.2
  firebase_messaging: ^6.0.16
  shared_preferences: ^0.5.8
  badges: ^1.1.1
  search_widget: ^1.0.2
  flutter_staggered_grid_view: ^0.3.0
  scroll_app_bar: ^1.0.2
  flutter_rating_bar: ^3.0.1+1
  auto_size_text: ^2.1.0
  lite_rolling_switch: ^0.1.1
  datetime_picker_formfield: ^1.0.0
  intro_slider: ^2.3.1
  esys_flutter_share: ^1.0.2
  dropdown_search: ^0.4.4
  search_choices: ^1.0.17
  photo_view: ^0.10.0
  rflutter_alert: ^1.0.3
  flutter_launcher_icons: ^0.7.5
  url_launcher: ^5.5.2
  searchable_dropdown: ^1.1.3
  carousel_pro: ^1.0.0
  flutter_range_slider: "^1.5.0"
  cached_network_image: ^2.0.0
  sqflite: ^1.3.0
  http: ^0.12.2
  http_auth: ^0.3.0
  location: ^3.0.0
  animate_do: ^1.7.3
  flutter_datetime_picker: ^1.4.0
  connectivity: ^2.0.0
  animated_text_kit: ^2.5.1
  kkiapay_flutter_sdk: ^1.0.4
  random_color: ^1.0.5
  in_app_update: ^1.1.14
  optimized_cached_image: ^1.0.0
  show_drawer: ^1.0.0



























dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/1erchoix01.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico.ttf
          weight: 600
    - family: Regular
      fonts:
        - asset: assets/fonts/HelveticaNeueRegular.ttf
    - family: Thin
      fonts:
        - asset: assets/fonts/HelveticaNeueThin.ttf
    - family: Bold
      fonts:
        - asset: assets/fonts/HelveticaNeuBold.ttf
    - family: Condensed
      fonts:
        - asset: assets/fonts/HelveticaNeueBlackCond.ttf
    - family: Light
      fonts:
        - asset: assets/fonts/HelveticaNeueLight.ttf
    - family: RobotoLight
      fonts:
        - asset: assets/fonts/RobotoLight.ttf
    - family: RobotoBold
      fonts:
        - asset: assets/fonts/RobotoBold.ttf
    - family: MonseraBold
      fonts:
        - asset: assets/fonts/MontserratBold.ttf
    - family: MonseraLight
      fonts:
        - asset: assets/fonts/Montserrat_Light.ttf
    - family: MonseraRegular
      fonts:
        - asset: assets/fonts/Montserrat_Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages